### ISSUE TITLE
Filesize, Resolution

### ISSUE THREAD

**Issue by subins2000** [facundobatista/certg#1]
Is there a config variable for optimizing the generated PDF ? and the resolution of the output image in the PDF ?

**Comment by facundobatista** [comment]
Hello subins2000,

Regarding optimization of the generated PDF, do you mean telling something specific to `inkscape` so when it generates the PDF does it so in a better way, or doing a post processing with other tool?

Regarding the resolution of the image inserted in the PDF (using the `images` directive in the `.yaml`), the image is used from the file "as is", no resolution is changed at all; note that the size in the resulting PDF is determined by the size of the original placement rectangle in the `.svg` file. Do you want something different to happen?

Thanks!

**Comment by subins2000** [comment]
@facundobatista Thank you for making this. It's really helpful !

My suggestion/feature request is to perhaps have a config variable for optimizing the generated PDF to reduce size. Changing the DPI of the generated PDF will reduce the size. I don't know if Inkscape has this option.

I'm now using ghostscript to compress the PDFs after generation. It would be nice instead to have that option in certg itself !

Here is how we're using certg for our FOSS club : https://gitlab.com/FOSSers/artwork/tree/master/certificates

Thanks :)

**Comment by facundobatista** [comment]
It's a good idea!

FTR, a good start is the content from this file: https://gitlab.com/FOSSers/artwork/blob/master/certificates/compress-pdfs.py

**Comment by subins2000** [comment]
Thank you for adding it !
